---
language: go
go:
- tip
- "1.10"
- "1.9"
- "1.8"
- "1.7"
- "1.6"
- "1.5"
- "1.4"
- "1.3"
- "1.2"
  # Code coverage started with go 1.2 :(
#- "1.1"
# Travis is broken: for "1.0" it launches with go 1.7.4
# https://travis-ci.org/dolmen-go/hexenc/jobs/342255514
# - "1.0"

before_install:
# "go get" supports "-t" only from go1.2
- go get $( [[ `go version` != *' go1.1 '* ]] && echo "-t" ) -v ./...
- [[ `go version` != *' go1.2 '* ]] || go get code.google.com/p/go.tools/cmd/cover

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
